# -*- coding: utf-8 -*-
"""test_api_client

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k2duhjsYhBXNxdmEf_rEHFasgTHlJHTO
"""

import os
try:
    from gradio_client import Client
except ImportError:
    print("Error: 'gradio_client' library not found. Please run 'pip install gradio_client' first.")
    exit()

# 1. Initialize the Client
# This connects to your specific deployment on Hugging Face Spaces
API_URL = "ruhameow/medical-soap-scribe"
client = Client(API_URL)

def run_test():
    print(f"--- Connecting to AIMScribe API at {API_URL} ---")

    # 2. Define a sample clinical dialogue (Bilingual example)
    test_input = "Patient: ডাক্তার, আমার ৩ দিন ধরে জ্বর। সাথে কাশিও আছে। Doctor: আচ্ছা, আপনার কি শ্বাসকষ্ট হচ্ছে? Patient: না, শুধু কাশি।"

    print(f"Sending Input: {test_input}\n")

    try:
        # 3. Call the predict function using the '/predict' endpoint
        result = client.predict(
            dialogue=test_input,
            api_name="/predict"
        )

        print("--- Generated SOAP Note ---")
        print(result)

    except Exception as e:
        print(f"An error occurred during inference: {e}")

if __name__ == "__main__":
    run_test()